spring:
  application:
    name: Stores

  datasource:
    url: jdbc:postgresql://localhost:5434/stores
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

application:
  security:
    jwt:
      secret-key: "unasecretamuylargaunasecretamuylargaunasecretamuylarga1234"